import { Inter, Jost } from 'next/font/google';
import './globals.css';

import Footer from '../components/Footer';
import Nav from '../components/Nav';

const baseFont = Inter({ subsets: ['latin'] });
const headerFont = Jost({
  subsets: ['latin'],
  weight: '500',
  display: 'swap',
  variable: '--font-headers',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${baseFont.className} ${headerFont.variable} bg-gray-50 text-slate-800`}>
        <div className='flex flex-col h-[100svh] px-4 md:px-6'>
          <Nav />
          <div className='flex-grow pt-6 mx-auto'>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
